version: "3.8"

services:
  appserver:
    image: local/php-web
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www:rw"
    environment:
      WWW_DATA_USER_UID: 1000
      WWW_DATA_GROUP_GID: 1000
